#!/bin/bash


start_install() {
    echo '1/2 : Création du volume glmf'
    docker volume create glmf
    echo "2/2 : Construction de l'image"
    docker build --tag md-auteur -f md-auteur/Dockerfile .
    
    echo ''
    echo 'Instructions :'
    echo '    1. Lancez md-auteur'
    echo '    2. Créez votre article avec glmf new <nom_article>'
    echo "    3. Générez l'archive à envoyer à la rédaction par glmf make dans le répertoire de l'article"
}


$(docker -v 2>&1 > /dev/null)
if [ ${?} -eq 0 ]; then
    echo "Installation dans le répertoire courant (${PWD})"
    while true; do
        read -p "Continuer (o/n) ? " yn
        case $yn in
            [Oo]* ) start_install; exit 0;;
            [Nn]* ) echo "Placez-vous dans le répertoire souhaité et renouvelez l'opération"; exit 1;;
            * ) echo 'Veuillez répondre par (o)ui ou (n)on';;
        esac
    done
else
    echo 'Vous devez installer Docker pour poursuivre...'
    exit 1
fi